spring:
  cloud:
    bus:
      enabled: true
      id: ${spring.application.name}:${server.port}
      kafka:
        enabled: true

    stream:
      default-binder: kafka
      function:
        definition: springCloudBusOutput
      bindings:
        springCloudBus-out-0:
          destination: springCloudBus
          binder: kafka
        toggle-updated-topic-out-0:
          destination: toggle-updated-topic
          binder: kafka
      kafka:
        bindings:
          springCloudBusOutput:
            producer:
              header-mode: payload